linux: &linux
  os: linux
  sudo: required
  language: python

osx: &osx
  os: osx
  language: generic
  osx_image: xcode9

addons:
  apt:
    packages:
      - python3
      - python3-dev

matrix:
  include:
    - <<: *linux
      python: 2.7
    - <<: *linux
      python: 3.6
    - <<: *osx
      env: PYTHON_VERSION=2.7.14
    - <<: *osx
      env: PYTHON_VERSION=3.6.4

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
